"""Increase owners.phone 15 chars -> 17 chars

Revision ID: 1ef2d5906fec
Revises: 96ca42c6802b
Create Date: 2025-08-12 12:36:36.507974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef2d5906fec'
down_revision: Union[str, Sequence[str], None] = '96ca42c6802b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=17),
               existing_comment='Номер телефона в международном формате',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'phone',
               existing_type=sa.String(length=17),
               type_=sa.VARCHAR(length=15),
               existing_comment='Номер телефона в международном формате',
               existing_nullable=True)
    # ### end Alembic commands ###
