"""Add autoincrement to manipulations.id

Revision ID: 96ca42c6802b
Revises: 
Create Date: 2025-08-12 01:12:01.727165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96ca42c6802b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('felis')
    op.drop_table('owners')
    op.drop_table('manipulation_facts')
    op.drop_table('pets')
    op.drop_table('manipulations')
    op.drop_table('species')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('species_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('species_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('species_id', name=op.f('species_pkey'))
    )
    op.create_table('manipulations',
    sa.Column('manipulations_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manipulations_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('manipulations_id', name=op.f('manipulations_pkey'))
    )
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('species', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pets_pkey'))
    )
    op.create_table('manipulation_facts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manipulation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_planned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('begin_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('manipulation_facts_pkey'))
    )
    op.create_table('owners',
    sa.Column('owner_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('owners_pkey'))
    )
    op.create_table('felis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('character', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('abilities', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('felis_pkey'))
    )
    # ### end Alembic commands ###
