"""Increase owners.phone 17 chars -> 32 chars

Revision ID: b1c78b87d114
Revises: 1ef2d5906fec
Create Date: 2025-08-12 12:39:40.588736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c78b87d114'
down_revision: Union[str, Sequence[str], None] = '1ef2d5906fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'phone',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=32),
               existing_comment='Номер телефона в международном формате',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=17),
               existing_comment='Номер телефона в международном формате',
               existing_nullable=True)
    # ### end Alembic commands ###
